version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5434:5432"
  back:
    image: ds-project
    container_name: ds-container
    restart: on-failure
    #command: cd /src && mkdir build && cd build && cmake .. && make && cd Main && ./main ../../Configs/Config.yml & cd ../../itests && python3 itests.py
    ports:
      - "8000:8000"
    network_mode: host
    volumes:
      - ./src:/src
  
  